In [ ]:
%pip install --upgrade google-cloud-vectorsearch fsspec gcsfs google-auth google-api-core

In [4]:
import google.auth
_, PROJECT_ID = google.auth.default()
LOCATION="asia-southeast1"
COLLECTION_ID="amazon-product-dataset-768-compact"

In [2]:
import pandas as pd
df_golden_product = pd.read_parquet('gs://jk-amazon-products-index/golden-records/amazon_products_golden.parquet')
df_golden_product

,id,vectors,product_type,item_name,item_keywords,item_description,data
0,00000529,"{'image_embedding': [-0.03478194, -0.005159070...",HOME,[DE] UMI Slim Laundry Basket on Wheels Tall Ro...,,[DE] UMI Slim Laundry Basket on Wheels Tall Ro...,{'description': '[DE] UMI Slim Laundry Basket ...
1,00003a93,"{'image_embedding': [-0.028530316, -0.03578147...",HOME,[ES] UMI. Essentials - Marco Doble para Sobrem...,#Marcos de Foto de estar dormitorio oficina cu...,[ES] UMI. Essentials - Marco Doble para Sobrem...,{'description': '[ES] UMI. Essentials - Marco ...
2,000088e1,"{'image_embedding': [-0.03092741, 0.0020457155...",LAUNDRY_HAMPER,[ES] Eono Amazon Brand Doble Bolsas Cestos par...,#Gran cesta de lavanderia lavado de ropa plega...,[ES] Eono Amazon Brand Doble Bolsas Cestos par...,{'description': '[ES] Eono Amazon Brand Doble ...
3,0000b301,"{'image_embedding': [0.009060884, -0.030949578...",HOME_FURNITURE_AND_DECOR,[MX] Stone & Beam Alfombra Moderna a Rayas,,[MX] Stone & Beam Alfombra Moderna a Rayas\n\n,{'description': '[MX] Stone & Beam Alfombra Mo...
4,0000b9b8,"{'image_embedding': [-0.044396702, -0.01553370...",WRENCH,[ES] AmazonBasics - Juego de llaves de trinque...,,[ES] AmazonBasics - Juego de llaves de trinque...,{'description': '[ES] AmazonBasics - Juego de ...
...,...,...,...,...,...,...,...
398184,ffff4040,"{'image_embedding': [-0.011574976, 0.01045859,...",CHAIR,[CA] AmazonBasics Multi-Purpose Adjustable Off...,#small #makeup #de #big #armless #medical #w/m...,[CA] AmazonBasics Multi-Purpose Adjustable Off...,{'description': '[CA] AmazonBasics Multi-Purpo...
398185,ffff87d7,"{'image_embedding': [-0.047705553, -0.05032951...",HUMIDIFIER,[IN] AmazonBasics Humidifier with Smart Auto-H...,#small #rooms #4010 #homech #humifiers #vicks ...,[IN] AmazonBasics Humidifier with Smart Auto-H...,{'description': '[IN] AmazonBasics Humidifier ...
398186,ffffc378,"{'image_embedding': [0.011752412, -0.017997367...",GROCERY,"[US] 365 Everyday Value, Raspberry Geranium Fr...",#sorbet #dessert #botanical #floral #flowers #...,"[US] 365 Everyday Value, Raspberry Geranium Fr...","{'description': '[US] 365 Everyday Value, Rasp..."
398187,ffffd5c6,"{'image_embedding': [-0.030390358, 0.003537298...",STORAGE_BAG,[ES] AmazonBasics 3-Bag Laundry Hamper Sorter ...,,[ES] AmazonBasics 3-Bag Laundry Hamper Sorter ...,{'description': '[ES] AmazonBasics 3-Bag Laund...
398188,ffffe50e,"{'image_embedding': [-0.002638914, 0.023899835...",HANDBAG,[MX] Amazon Brand - The Fix Hampton 2 Crossbod...,#accesorios bolso bolso bolso bolso sacos seño...,[MX] Amazon Brand - The Fix Hampton 2 Crossbod...,{'description': '[MX] Amazon Brand - The Fix H...

In [9]:
set(df_golden_product['product_type'].tolist())

{'ABIS_BEAUTY',
 'ABIS_BOOK',
 'ABIS_DRUGSTORE',
 'ABIS_ELECTRONICS',
 'ABIS_HOME_IMPROVEMENT',
 'ABIS_KITCHEN',
 'ABIS_LAWN_AND_GARDEN',
 'ABIS_PET_PRODUCTS',
 'ABIS_VIDEO_GAMES',
 'ACCESSORY',
 'ACCESSORY_OR_PART_OR_SUPPLY',
 'AGRICULTURAL_SUPPLIES',
 'AIR_COMPRESSOR',
 'AIR_CONDITIONER',
 'AIR_FRYER',
 'AIR_MATTRESS',
 'AIR_PUMP',
 'AIR_PURIFIER',
 'AMAZON_BOOK_READER_ACCESSORY',
 'AMAZON_TABLET_ACCESSORY',
 'ANIMAL_COLLAR',
 'ANIMAL_LITTER',
 'ANTENNA',
 'AREA_DEODORIZER',
 'ARTIFICIAL_PLANT',
 'ARTIFICIAL_TREE',
 'ART_AND_CRAFT_SUPPLY',
 'ASTRINGENT_SUBSTANCE',
 'AUDIO_OR_VIDEO',
 'AUTO_ACCESSORY',
 'AUTO_CHEMICAL',
 'AUTO_OIL',
 'AUTO_PART',
 'AV_FURNITURE',
 'AV_RECEIVER',
 'BABY_BOTTLE',
 'BABY_PRODUCT',
 'BACKPACK',
 'BADGE_HOLDER',
 'BAG',
 'BAKEWARE',
 'BAKING_CUP',
 'BAKING_MIX',
 'BAKING_PAN',
 'BAKING_PAPER',
 'BARBECUE_GRILL',
 'BARBELL',
 'BASKET',
 'BATHWATER_ADDITIVE',
 'BATTERY',
 'BEAN_BAG_CHAIR',
 'BEAUTY',
 'BED',
 'BED_FRAME',
 'BENCH',
 'BINOCULAR',
 'BISS',
 'BLANKET',
 'BLANK_MEDIA',
 'BLOOD_PRESSURE_MONITOR',
 'BODY_DEODORANT',
 'BODY_LUBRICANT',
 'BODY_POSITIONER',
 'BOOKEND',
 'BOOT',
 'BOTTLE',
 'BOTTLE_OPENER',
 'BOTTLE_RACK',
 'BOXING_GLOVE',
 'BRACELET',
 'BREAD',
 'BREAD_MAKING_MACHINE',
 'BREAKFAST_CEREAL',
 'BROOM',
 'BUCKET',
 'BUILDING_MATERIAL',
 'CABINET',
 'CADDY',
 'CAKE',
 'CALCULATOR',
 'CAMCORDER',
 'CAMERA_BAGS_AND_CASES',
 'CAMERA_FLASH',
 'CAMERA_LENS_FILTERS',
 'CAMERA_OTHER_ACCESSORIES',
 'CAMERA_SUPPORT',
 'CAMERA_TRIPOD',
 'CANDLE',
 'CANDLE_HOLDER',
 'CANDY',
 'CAN_OPENER',
 'CARD_STOCK',
 'CARGO_STRAP',
 'CARRYING_CASE_OR_BAG',
 'CAR_AUDIO_OR_THEATER',
 'CAR_ELECTRONICS',
 'CASSEROLES',
 'CELLULAR_PHONE',
 'CELLULAR_PHONE_CASE',
 'CE_ACCESSORY',
 'CE_CARRYING_CASE_OR_BAG',
 'CHAIR',
 'CHANGING_PAD_COVER',
 'CHARGING_ADAPTER',
 'CHARM',
 'CHILDRENS_COSTUME',
 'CHOCOLATE_CANDY',
 'CLEANING_AGENT',
 'CLEANING_BRUSH',
 'CLOCK',
 'CLOTHES_HANGER',
 'CLOTHES_RACK',
 'COFFEE',
 'COFFEE_MAKER',
 'COMPUTER',
 'COMPUTER_ADD_ON',
 'COMPUTER_COMPONENT',
 'COMPUTER_COOLING_DEVICE',
 'COMPUTER_DRIVE_OR_STORAGE',
 'COMPUTER_INPUT_DEVICE',
 'COMPUTER_INPUT_DEVICE_ACCESSORY',
 'COMPUTER_SPEAKER',
 'CONDIMENT',
 'CONDITIONER',
 'CONSUMER_ELECTRONICS',
 'COOKIE',
 'COOKIE_CUTTER',
 'COOKING_OVEN',
 'COSMETIC_BRUSH',
 'COSMETIC_CASE',
 'COSMETIC_POWDER',
 'COUNTERTOP_BURNER',
 'COUNTERTOP_GRIDDLE_APPLIANCE',
 'COUNTERTOP_OVEN',
 'CRACKER',
 'CURTAIN',
 'CUTTING_BOARD',
 'DAIRY_BASED_BUTTER',
 'DAIRY_BASED_CHEESE',
 'DAIRY_BASED_CREAM',
 'DAIRY_BASED_DRINK',
 'DAIRY_BASED_ICE_CREAM',
 'DEEP_FRYER',
 'DEHUMIDIFIER',
 'DESK',
 'DIETARY_SUPPLEMENTS',
 'DIGITAL_DEVICE_3',
 'DINNERWARE',
 'DISHWARE_BOWL',
 'DISHWARE_PLACE_SETTING',
 'DISHWARE_PLATE',
 'DISHWASHER',
 'DISHWASHER_DETERGENT',
 'DOORSTOP',
 'DRESSER',
 'DRILL',
 'DRILL_BITS',
 'DRINKING_CUP',
 'DRINKING_STRAW',
 'DRINK_COASTER',
 'DRINK_FLAVORED',
 'DRYING_RACK',
 'DUTCH_OVENS',
 'EARMUFF',
 'EARPLUG',
 'EARRING',
 'EDIBLE_OIL_VEGETABLE',
 'EDUCATIONAL_SUPPLIES',
 'ELECTRIC_FAN',
 'ELECTRIC_WATER_BOILER',
 'ELECTROMECHANICAL_GAUGE',
 'ELECTRONIC_ADAPTER',
 'ELECTRONIC_CABLE',
 'ELECTRONIC_DEVICE_DOCKING_STATION',
 'ELECTRONIC_SWITCH',
 'ENVELOPE',
 'ESSENTIAL_OIL',
 'EXERCISE_BAND',
 'EXERCISE_MAT',
 'EYEBROW_COLOR',
 'EYELID_COLOR',
 'EYEWEAR',
 'FACE_SHAPING_MAKEUP',
 'FACIAL_TISSUE',
 'FASHIONEARRING',
 'FASHIONNECKLACEBRACELETANKLET',
 'FASHIONOTHER',
 'FASHIONRING',
 'FASTENER_DRIVE_BIT',
 'FAUCET',
 'FIGURINE',
 'FILE_FOLDER',
 'FINEEARRING',
 'FINENECKLACEBRACELETANKLET',
 'FINEOTHER',
 'FINERING',
 'FIRST_AID_KIT',
 'FISH',
 'FISHING_EQUIPMENT',
 'FITNESS_BENCH',
 'FLASH_DRIVE',
 'FLASH_MEMORY',
 'FLATWARE',
 'FLAT_SCREEN_DISPLAY_MOUNT',
 'FLAT_SHEET',
 'FLAVORED_DRINK_CONCENTRATE',
 'FLOUR',
 'FOOD_BLENDER',
 'FOOD_DEHYDRATOR',
 'FOOD_MIXER',
 'FOOD_PREPARATION_MOLD',
 'FOOD_PROCESSOR',
 'FOOD_SERVICE_SUPPLY',
 'FOOD_SLICER',
 'FOOD_STORAGE_BAG',
 'FOUNTAIN',
 'FREESTANDING_SHELTER',
 'FRUIT',
 'FRUIT_SNACK',
 'FUEL_PUMP',
 'FURNITURE',
 'FURNITURE_COVER',
 'FURNITURE_LINER',
 'GAME_DICE',
 'GARLIC_PRESS',
 'GOLF_CLUB',
 'GOLF_CLUB_BAG',
 'GPS_OR_NAVIGATION_ACCESSORY',
 'GPS_OR_NAVIGATION_SYSTEM',
 'GROCERY',
 'GUITARS',
 'HAIR_BRUSH',
 'HAIR_CLEANER_CONDITIONER',
 'HAIR_COLORING_AGENT',
 'HAIR_COMB',
 'HAIR_IRON',
 'HAIR_REMOVAL_AGENT',
 'HAIR_STYLING_AGENT',
 'HANDBAG',
 'HARDWARE',
 'HARDWARE_CLAMP_VISE',
 'HARDWARE_HANDLE',
 'HARDWARE_HINGE',
 'HARDWARE_TUBING',
 'HAT',
 'HEADBOARD',
 'HEADPHONES',
 'HEALTH_PERSONAL_CARE',
 'HERB',
 'HERBAL_SUPPLEMENT',
 'HOME',
 'HOME_BED_AND_BATH',
 'HOME_FURNITURE_AND_DECOR',
 'HOME_LIGHTING_ACCESSORY',
 'HOME_LIGHTING_AND_LAMPS',
 'HOME_MIRROR',
 'HOME_ORGANIZERS_AND_STORAGE',
 'HONEY',
 'HUMIDIFIER',
 'ICE_CHEST',
 'ICE_CUBE_TRAY',
 'INCENSE',
 'INFANT_TODDLER_CAR_SEAT',
 'INKJET_PRINTER_INK',
 'INK_OR_TONER',
 'INPUT_MOUSE',
 'INPUT_PEN',
 'INSTRUMENT_PARTS_AND_ACCESSORIES',
 'JANITORIAL_SUPPLY',
 'JAR',
 'JERKY',
 'JEWELRY',
 'JEWELRY_SET',
 'JEWELRY_STORAGE',
 'JUICER',
 'JUICE_AND_JUICE_DRINK',
 'KEYBOARDS',
 'KICK_SCOOTER',
 'KITCHEN',
 'KITCHEN_KNIFE',
 'KITCHEN_TOOLS',
 'KNIFE_BLOCK_SET',
 'LABEL',
 'LAB_SUPPLY',
 'LADDER',
 'LAMP',
 'LANDLINE_PHONE',
 'LAUNDRY_APPLIANCE',
 'LAUNDRY_DETERGENT',
 'LAUNDRY_HAMPER',
 'LEAVENING_AGENT',
 'LEGUME',
 'LEHENGA_CHOLI_SET',
 'LEOTARD',
 'LICENSE_PLATE_ATTACHMENT',
 'LIGHT_BULB',
 'LIGHT_FIXTURE',
 'LIGHT_SOURCE',
 'LIP_BALM',
 'LIP_COLOR',
 'LITTER_BOX',
 'LOCK',
 'LUGGAGE',
 'MAJOR_HOME_APPLIANCES',
 'MANUAL_SHAVING_RAZOR',
 'MARKING_PEN',
 'MASCARA',
 'MASSAGER',
 'MASSAGE_STICK',
 'MATTRESS',
 'MEAL_HOLDER',
 'MEAT',
 'MECHANICAL_COMPONENTS',
 'MECHANICAL_LIGHTER',
 'MEDIA_STORAGE',
 'MEDICATION',
 'MEMORY_READER',
 'MICROPHONE',
 'MICROSCOPES',
 'MICROWAVE_OVEN',
 'MILK_SUBSTITUTE',
 'MINERAL_SUPPLEMENT',
 'MONITOR',
 'MOUSE_PAD',
 'MOUTHWASH',
 'MULTIPORT_HUB',
 'MULTITOOL',
 'MUSCLE_ROLLER',
 'NAIL_POLISH',
 'NECKLACE',
 'NECKTIE',
 'NETWORKING_DEVICE',
 'NETWORKING_ROUTER',
 'NETWORK_INTERFACE_CONTROLLER_ADAPTER',
 'NON_DAIRY_CREAM',
 'NON_RIDING_TOY_VEHICLE',
 'NOODLE',
 'NOTEBOOK_COMPUTER',
 'NUTRITIONAL_SUPPLEMENT',
 'NUTS',
 'NUT_BUTTER',
 None,
 'OFFICE_ELECTRONICS',
 'OFFICE_PRODUCTS',
 'ORTHOPEDIC_BRACE',
 'OTC_MEDICATION',
 'OTTOMAN',
 'OUTBUILDING',
 'OUTDOOR_LIVING',
 'OUTDOOR_RECREATION_PRODUCT',
 'OVERALLS',
 'PACIFIER',
 'PACKAGED_SOUP_AND_STEW',
 'PANTRY',
 'PAPER_PRODUCT',
 'PAPER_TOWEL_HOLDER',
 'PASTRY',
 'PERCUSSION_INSTRUMENTS',
 'PERSONAL_CARE_APPLIANCE',
 'PERSONAL_COMPUTER',
 'PERSONAL_PILL_DISPENSER',
 'PET_APPAREL',
 'PET_PEST_CONTROL',
 'PET_SUPPLIES',
 'PET_TOY',
 'PHONE',
 'PHONE_ACCESSORY',
 'PICTURE_FRAME',
 'PILLOW',
 'PINBOARD',
 'PITCHER',
 'PLACEMAT',
 'PLANTER',
 'PLIERS',
 'PLUMBING_FIXTURE',
 'POPCORN',
 'PORTABLE_AUDIO',
 'PORTABLE_AV_DEVICE',
 'PORTABLE_ELECTRONIC_DEVICE_COVER',
 'PORTABLE_ELECTRONIC_DEVICE_MOUNT',
 'PORTABLE_ELECTRONIC_DEVICE_STAND',
 'PORTABLE_STOVE',
 'PORTABLE_TOOL_BOX',
 'POT_HOLDER',
 'POULTRY',
 'POWERSPORTS_VEHICLE_PART',
 'POWER_BANK',
 'POWER_CONVERTER',
 'POWER_STRIP',
 'POWER_SUPPLIES_OR_PROTECTION',
 'PRESSURE_COOKER',
 'PRETZEL',
 'PRINTER',
 'PRINT_COPY_PAPER',
 'PROFESSIONAL_HEALTHCARE',
 'PROTEIN_DRINK',
 'PROTEIN_SUPPLEMENT_POWDER',
 'PUMP_DISPENSER',
 'PUNCHING_BAG',
 'PUZZLES',
 'RADIO',
 'RAZOR_BLADE_CARTRIDGE',
 'RECEIVER_OR_AMPLIFIER',
 'RECREATION_BALL',
 'REFRIGERATION_APPLIANCE',
 'REFRIGERATOR',
 'REMOTE_CONTROL',
 'RICE_COOKERS',
 'RICE_MIX',
 'RING',
 'ROASTING_PAN',
 'ROOM_DIVIDER',
 'ROWING_MACHINE',
 'RUG',
 'RUG_PAD',
 'SAFE',
 'SAFETY_GLASSES',
 'SAFETY_SUPPLY',
 'SALAD_DRESSING',
 'SALWAR_SUIT_SET',
 'SANDAL',
 'SAUCE',
 'SAUTE_FRY_PAN',
 'SAW_BLADE',
 'SCANNER',
 'SCISSORS',
 'SCREEN_PROTECTOR',
 'SCREWDRIVER',
 'SCULPTURE',
 'SEALS',
 'SECURITY_CAMERA',
 'SECURITY_ELECTRONICS',
 'SELF_STICK_NOTE',
 'SHAMPOO',
 'SHEET_PAN',
 'SHELF',
 'SHELLFISH',
 'SHIPPING_BOX',
 'SHOES',
 'SHOE_INSERT',
 'SHOVEL_SPADE',
 'SHOWERHEAD',
 'SKATEBOARD',
 'SKIN_CLEANING_AGENT',
 'SKIN_CLEANING_WIPE',
 'SKIN_EXFOLIANT',
 'SKIN_FOUNDATION_CONCEALER',
 'SKIN_MOISTURIZER',
 'SKIN_TREATMENT_MASK',
 'SLEEPING_BAG',
 'SLEEP_MASK',
 'SLOW_COOKER',
 'SMALL_HOME_APPLIANCES',
 'SNACK_CHIP_AND_CRISP',
 'SNACK_FOOD_BAR',
 'SNACK_MIX',
 'SOFA',
 'SOUND_AND_RECORDING_EQUIPMENT',
 'SOUS_VIDE_MACHINE',
 'SPEAKERS',
 'SPIRITS',
 'SPORTING_GOODS',
 'SPORT_RACKET',
 'SPORT_TABLE_GAME',
 'STAPLER',
 'STATIONARY_BICYCLE',
 'STEERING_WHEEL_COVER',
 'STICKER_DECAL',
 'STOOL_SEATING',
 'STORAGE_BAG',
 'STORAGE_BINDER',
 'STORAGE_BOX',
 'STORAGE_DRAWER',
 'STORAGE_HOOK',
 'STORAGE_RACK',
 'STRINGED_INSTRUMENTS',
 'STRING_LIGHT',
 'STROLLER',
 'SUGAR',
 'SUGAR_CANDY',
 'SUGAR_SUBSTITUTE',
 'SUITCASE',
 'SUNGLASSES',
 'SUNSCREEN',
 'SURVEILANCE_SYSTEMS',
 'SUSPENDER',
 'SWATCH',
 'SWEATBAND',
 'SWING',
 'SYSTEM_POWER_DEVICE',
 'TABLE',
 'TABLETOP_GAME',
 'TEA',
 'TEACHING_EQUIPMENT',
 'TECHNICAL_SPORT_SHOE',
 'TELESCOPE',
 'TELEVISION',
 'TENT',
 'TERMINAL_BLOCK',
 'THERMOMETER',
 'THERMOPLASTIC_FILAMENT',
 'THERMOS',
 'THICKENING_AGENT',
 'TIMER',
 'TOASTER',
 'TOILET_PAPER_HOLDER',
 'TOILET_SEAT',
 'TOOLS',
 'TOOTHBRUSH',
 'TOOTHBRUSH_HOLDER',
 'TOOTH_CLEANING_AGENT',
 'TOTE_BAG',
 'TOWEL_HOLDER',
 'TOYS_AND_GAMES',
 'TOY_BUILDING_BLOCK',
 'TOY_FIGURE',
 'TOY_SLIME',
 'TRACK_SUIT',
 'TRANSPORT_RACK',
 'TRASH_CAN',
 'TREADMILL',
 'TWO_WAY_RADIO',
 'UMBRELLA',
 'UTILITY_CART_WAGON',
 'UTILITY_KNIFE',
 'VACUUM_CLEANER',
 'VACUUM_SEALER_MACHINE',
 'VALVE',
 'VASE',
 'VEGETABLE',
 'VEHICLE_INTERIOR_SHADE',
 'VEHICLE_LIGHT_ASSEMBLY',
 'VEHICLE_LIGHT_BULB',
 'VEHICLE_MIRROR',
 'VEHICLE_SAFETY_CAMERA',
 'VEHICLE_SCAN_TOOL',
 'VEHICLE_SEAT_COVER',
 'VEST',
 'VIDEO_DEVICE',
 'VIDEO_GAME_ACCESSORIES',
 'VIDEO_PROJECTOR',
 'VINE',
 'VINEGAR',
 'VITAMIN',
 'VIVARIUM',
 'WAIST_CINCHER',
 'WALKING_STICK',
 'WALLET',
 'WALLPAPER',
 'WALL_ART',
 'WASHER_DRYER_COMBINATION',
 'WASTE_BAG',
 'WATCH',
 'WATER',
 'WATER_FLOTATION_DEVICE',
 'WATER_PUMP',
 'WATER_PURIFICATION_UNIT',
 'WEIGH_SCALE',
 'WHEEL',
 'WHEEL_CUTTER',
 'WILDLIFE_FEEDER',
 'WINDOW_SHADE',
 'WINE',
 'WIRELESS_ACCESSORY',
 'WIRELESS_LOCKED_PHONE',
 'WOUND_DRESSING',
 'WRENCH',
 'WRITING_BOARD',
 'WRITING_INSTRUMENT',
 'WRITING_PAPER'}

In [3]:
product_filter = [
    # 가전 / 디지털 / IT
    'CELLULAR_PHONE', 'NOTEBOOK_COMPUTER', 
    'PERSONAL_COMPUTER', 'MONITOR', 'KEYBOARDS', 'INPUT_MOUSE', 
    'HEADPHONES', 'SPEAKERS', 'COMPUTER_SPEAKER', 'MICROPHONE', 'TELEVISION', 
    'REMOTE_CONTROL', 'BATTERY', 'POWER_BANK', 'CHARGING_ADAPTER', 'FLASH_DRIVE', 
    'WEIGH_SCALE', 'CLOCK', 'SECURITY_CAMERA',
    
    # 주방 / 식기    
    'KITCHEN_KNIFE', 'SCISSORS', 'CAN_OPENER', 'BOTTLE_OPENER', 
    'DINNERWARE', 'DISHWARE_PLATE', 'DISHWARE_BOWL', 'DRINKING_CUP', 
    'FLATWARE', 'DRINKING_STRAW', 'DRINK_COASTER', 'PITCHER', 'THERMOS', 
    'PLACEMAT', 'POT_HOLDER', 'BOTTLE_RACK', 'DRYING_RACK', 'FOOD_STORAGE_BAG',

    # 뷰티 / 생활용품 / 위생
    'HAIR_BRUSH', 'HAIR_COMB', 'HAIR_IRON', 
    'SKIN_CLEANING_AGENT', 'SKIN_MOISTURIZER', 'SKIN_EXFOLIANT', 'SKIN_TREATMENT_MASK', 
    'SUNSCREEN', 'LIP_BALM', 'TOOTHBRUSH', 'TOOTH_CLEANING_AGENT', 
    'MOUTHWASH', 'FACIAL_TISSUE', 'SKIN_CLEANING_WIPE', 'CLEANING_AGENT', 
    'CLEANING_BRUSH', 'BROOM', 'MASCARA', 'NAIL_POLISH',

    # 식품 / 음료 / 식재료
    'WATER', 'COFFEE', 'TEA', 'JUICE_AND_JUICE_DRINK', 'MILK_SUBSTITUTE', 
    'BREAD', 'COOKIE', 'CAKE', 'PASTRY', 'CRACKER', 'PRETZEL', 
    'POPCORN', 'CANDY', 'CHOCOLATE_CANDY', 'SUGAR_CANDY', 'SNACK_CHIP_AND_CRISP', 
    'SNACK_FOOD_BAR', 'BREAKFAST_CEREAL', 'NOODLE', 'RICE_MIX', 'PACKAGED_SOUP_AND_STEW', 
    'MEAT', 'POULTRY', 'FISH', 'SHELLFISH', 'VEGETABLE', 'FRUIT', 
    'NUTS', 'LEGUME', 'FLOUR', 'SUGAR', 'SUGAR_SUBSTITUTE', 'HONEY', 
    'EDIBLE_OIL_VEGETABLE', 'DAIRY_BASED_BUTTER', 'DAIRY_BASED_CHEESE', 'DAIRY_BASED_CREAM', 
    'SAUCE', 'SALAD_DRESSING', 'VINEGAR', 'WINE',

    # 가구 / 인테리어 / 수납
    'BLANKET', 'SOFA', 'CHAIR', 'DESK', 'TABLE', 'BENCH',  
    'CABINET', 'SHELF', 'CURTAIN', 'HOME_MIRROR', 
    'VASE', 'TRASH_CAN', 'STORAGE_BOX', 'STORAGE_BAG',

    # 패션잡화 / 취미 / 반려용품
    'SHOES', 'SANDAL', 'BOOT', 'BAG', 'BACKPACK', 
    'HANDBAG', 'TOTE_BAG', 'WALLET', 'WATCH', 'SUNGLASSES', 'EARRING', 'NECKLACE', 'BRACELET', 
    'RING', 

    # 문구 / 공구 / 건강 / 기타
    'WRITING_INSTRUMENT', 'STAPLER', 'SELF_STICK_NOTE', 'LOCK', 'VITAMIN', 
    'DIETARY_SUPPLEMENTS', 'FIRST_AID_KIT']
df_compact_products = df_golden_product[df_golden_product['product_type'].isin(product_filter)]
df_compact_products

,id,vectors,product_type,item_name,item_keywords,item_description,data
11,0001c52d,"{'image_embedding': [-0.019685043, -0.00303021...",CHAIR,[US] Stone & Beam S&B GF GF-80933G Vintage Sil...,#big #heavyweight #no #basics #espo #allsteel ...,[US] Stone & Beam S&B GF GF-80933G Vintage Sil...,{'description': '[US] Stone & Beam S&B GF GF-8...
12,00020b5a,"{'image_embedding': [-0.041058376, -0.03353369...",SHOES,[AU] find. Women's Kitten Heel Court Closed-To...,"#heel,kitten,pump,woman,women #UK #UK #UK #UK ...",[AU] find. Women's Kitten Heel Court Closed-To...,{'description': '[AU] find. Women's Kitten Hee...
13,00020b94,"{'image_embedding': [-0.019196399, 0.020137342...",EARRING,[JP] [アマゾンコレクション] Amazon Collection 14Kイエローゴール...,#イヤリングスタッドフープゴールドハローフック真珠ジュエリーブラック小さなヴィンテージオパー...,[JP] [アマゾンコレクション] Amazon Collection 14Kイエローゴール...,{'description': '[JP] [アマゾンコレクション] Amazon Coll...
19,00033168,"{'image_embedding': [-0.004150736, 0.018715905...",CHAIR,[MX] Strathwood Basics - Silla acolchada de po...,#Jugar #Grande #Tienda #Joe #camping #Rosa #Pl...,[MX] Strathwood Basics - Silla acolchada de po...,{'description': '[MX] Strathwood Basics - Sill...
20,0003658b,"{'image_embedding': [0.017919777, 0.00344414, ...",CRACKER,"[US] 365 Everyday Value, Oyster Crackers, 8 oz",,"[US] 365 Everyday Value, Oyster Crackers, 8 oz...","{'description': '[US] 365 Everyday Value, Oyst..."
...,...,...,...,...,...,...,...
398166,fffb48d7,"{'image_embedding': [0.001306995, 0.019842863,...",SHOES,[IN] Bourge Men's Magic-20 Navy Sneakers-11 UK...,#footwear #casual #gents #daily #casual #daily...,[IN] Bourge Men's Magic-20 Navy Sneakers-11 UK...,{'description': '[IN] Bourge Men's Magic-20 Na...
398180,fffe67d0,"{'image_embedding': [-0.057308294, 0.02074126,...",SHOES,[IN] Amazon Brand - Symbol Women's Tan Fashion...,#bellies for women stylish #shoes for women st...,[IN] Amazon Brand - Symbol Women's Tan Fashion...,{'description': '[IN] Amazon Brand - Symbol Wo...
398184,ffff4040,"{'image_embedding': [-0.011574976, 0.01045859,...",CHAIR,[CA] AmazonBasics Multi-Purpose Adjustable Off...,#small #makeup #de #big #armless #medical #w/m...,[CA] AmazonBasics Multi-Purpose Adjustable Off...,{'description': '[CA] AmazonBasics Multi-Purpo...
398187,ffffd5c6,"{'image_embedding': [-0.030390358, 0.003537298...",STORAGE_BAG,[ES] AmazonBasics 3-Bag Laundry Hamper Sorter ...,,[ES] AmazonBasics 3-Bag Laundry Hamper Sorter ...,{'description': '[ES] AmazonBasics 3-Bag Laund...
398188,ffffe50e,"{'image_embedding': [-0.002638914, 0.023899835...",HANDBAG,[MX] Amazon Brand - The Fix Hampton 2 Crossbod...,#accesorios bolso bolso bolso bolso sacos seño...,[MX] Amazon Brand - The Fix Hampton 2 Crossbod...,{'description': '[MX] Amazon Brand - The Fix H...

In [6]:
!gcloud storage buckets create gs://$PROJECT_ID-vs2 --location=asia-southeast1

Creating gs://sandbox-373102-vs2/...

In [7]:
# 원하는 컬럼('id', 'vectors')만 선택하여 JSONL로 저장
df_compact_products[['id', 'data', 'vectors']].to_json(f'gs://{PROJECT_ID}-vs2/data/amazon-product-dataset-768-compact.jsonl', orient='records', lines=True, force_ascii=False)

In [ ]:
from google.cloud import vectorsearch_v1beta

# Create the client
vector_search_service_client = vectorsearch_v1beta.VectorSearchServiceClient()

# The JSON schema for the data
data_schema = {
    "type": "object",
    "properties": {
        "name": {"type": "string"},
        "description": {"type": "string"},
    },
}

# The JSON schema for the vector
vector_schema = {
    "image_embedding": {"dense_vector": {"dimensions": 768}},
    "text_embedding": {"dense_vector": {"dimensions": 768}}
}

collection = vectorsearch_v1beta.Collection(
    data_schema=data_schema,
    vector_schema=vector_schema,
)
request = vectorsearch_v1beta.CreateCollectionRequest(
    parent=f"projects/{PROJECT_ID}/locations/{LOCATION}",
    collection_id=COLLECTION_ID,
    collection=collection,
)

# Create the collection
operation = vector_search_service_client.create_collection(request=request)

# Wait for the result (note this may take up to several minutes)
operation.result()

In [ ]:
from datetime import datetime
from google.cloud import vectorsearch_v1

# Create the client
vector_search_service_client = vectorsearch_v1.VectorSearchServiceClient()

# Initialize request
request = vectorsearch_v1.ImportDataObjectsRequest(
    name=f"projects/{PROJECT_ID}/locations/{LOCATION}/collections/{COLLECTION_ID}",
    gcs_import={
      "contents_uri": f"gs://{PROJECT_ID}-vs2/data/",
      "error_uri": f"gs://{PROJECT_ID}-vs2/error/",
    },
)

# Make the request
print(datetime.now()) 
operation = vector_search_service_client.import_data_objects(request=request)

In [ ]:
import time
while operation.done() == False:
    time.sleep(1)
print(datetime.now())

In [ ]:
from google.cloud import vectorsearch_v1beta

# Create a client
client = vectorsearch_v1beta.VectorSearchServiceClient()

operations = []
# Initialize request argument(s)
for index_field in ["image_embedding", "text_embedding"]:
    index = vectorsearch_v1beta.Index(
        index_field=index_field,
        #filter_fields=["year", "genre"],
        store_fields=["name", "description"],
    )
    request = vectorsearch_v1beta.CreateIndexRequest(
        parent=f"projects/{PROJECT_ID}/locations/{LOCATION}/collections/{COLLECTION_ID}",
        index_id=f"idx-{index_field.replace('_', '-')}-amazon-product-dataset-768-compact",
        index=index,
    )
    
    # Make the request
    operations.append(client.create_index(request=request))
print(datetime.now())

In [ ]:
while not all(operation.done() for operation in operations):
    time.sleep(1)    
print(datetime.now())